name: oraah_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <3.4.5 '


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  connectivity_plus: ^5.0.1
  get_it: ^7.6.4
  animated_splash_screen: ^1.3.0
  flutter_native_splash: ^2.3.4
  page_transition: ^2.1.0
  shared_preferences: ^2.2.2
  get: ^4.6.6


flutter_native_splash:
  android: true
  ios: true
  web: false
  background_image: assets/bg.png
  image:  assets/logo.png
  fullscreen: true
  android_12:
    image: assets/logo.png
    background_image: assets/bg.png
    icon_background_color: "#101636"
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  
  line_awesome_flutter: ^2.0.0
  google_fonts: ^5.1.0
  dio: ^5.3.2
  cached_network_image: ^3.2.3
  loading_animation_widget: ^1.2.0+4
  auto_size_text: ^3.0.0
  path_provider: ^2.1.0
  clipboard: ^0.1.3
  share_plus: ^7.1.0
#  screenshot: ^2.1.0
  image_gallery_saver: ^2.0.3
  permission_handler: ^10.4.3
  lottie: ^2.6.0
  flutter_lints: ^2.0.0




flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo/
    - assets/images/
    - assets/lottie/






